version: 2

updates:
  - allow:
      - dependency-type: direct
    commit-message:
      include: scope
      prefix: chore
    directory: /
    open-pull-requests-limit: 99
    package-ecosystem: github-actions
    reviewers:
      - 'ridedott/platform'
    schedule:
      interval: daily
  - allow:
      - dependency-type: direct
    commit-message:
      include: scope
      prefix: chore
    directory: /
    ignore:
      # https://github.com/ridedott/merge-me-action/issues/1098
      - dependency-name: '@vercel/ncc'
        versions: ['^0.31.0']
    open-pull-requests-limit: 99
    package-ecosystem: npm
    reviewers:
      - 'ridedott/platform'
    schedule:
      interval: daily
    versioning-strategy: increase
