env:
  es6: true
  node: true
extends: '@ridedott/eslint-config'
overrides:
  - env:
      jest: true
    files:
      - src/**/*.spec.ts
    rules:
      '@typescript-eslint/camelcase': 'off'
      '@typescript-eslint/no-magic-numbers': 'off'
      'max-lines': 'off'
      max-lines-per-function: 'off'
      no-magic-numbers: 'off'
parserOptions:
  ecmaVersion: 2020
  project: tsconfig.json
  sourceType: module
rules:
  no-negated-condition: 'off'
