env:
  es6: true
  node: true
extends: '@ridedott/eslint-config'
overrides:
  - env:
      jest: true
    files:
      - src/**/*.spec.ts
    rules:
      '@typescript-eslint/camelcase': 'off'
      '@typescript-eslint/no-magic-numbers': 'off'
      jest/require-hook: 'error'
      max-lines: 'off'
      max-lines-per-function: 'off'
      no-magic-numbers: 'off'
      max-statements: 'off'
  - files:
      - src/**/computeRequiresStrictStatusChecksForRefs.*
    rules:
      'unicorn/prevent-abbreviations': 'off'
parserOptions:
  ecmaVersion: 2020
  project: tsconfig.json
  sourceType: module
rules:
  jest/require-hook: 'off'
  no-negated-condition: 'off'
