name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js with GitHub Package Registry
        uses: actions/setup-node@v1
        with:
          node-version: 12
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          registry-url: 'https://npm.pkg.github.com'
          scope: 'ridedott'
          always-auth: true
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          key:
            npm-${{ hashFiles(format('{0}{1}', github.workspace,
            '/package-lock.json')) }}
          path: ~/.npm
          restore-keys: |
            npm-
      - name: Install dependencies
        run:
          npm ci --ignore-scripts --no-audit --prefer-offline --progress=false
      - name: Build
        run: |
          # Workaround https://github.com/zeit/ncc/issues/457.
          mv tsconfig.production.json tsconfig.json
          npm run build
      - name: Release
        env:
          # This must be used as GitHub Actions token does not support pushing
          # to protected branches.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_WORKAROUND }}
        run: |
          sed -i.bak -e '/dist/d' .gitignore
          npx semantic-release
